### ISSUE TITLE
Which SLAM did you generate for ground-truth?

### ISSUE THREAD

**Issue by yinhaosen** [TIERS/tiers-lidars-dataset-enhanced#2]
I didn't find which slam did you use to generate ground-truth for each dataset?

**Comment by Qingq-li** [comment]
Hi, thanks for your interest in our work.  The ground-truth data for indoor sequences, where MOCAP and GNSS/RTK are unavailable,  are generated by NDT matching real-time pointcloud with a High-definition map.  We explained how we build an HD map with solid-state lidar in the preprint paper here:https://arxiv.org/abs/2210.00812.  You will get more details on how we built this dataset from the paper.
