### ISSUE TITLE
GPS sensor extrinsic

### ISSUE THREAD

**Issue by mertyavuz41** [TIERS/tiers-lidars-dataset-enhanced#6]
Hi,

First of all I would like to thank a lot for great works. 

I have examine README.rd and full of paper but I couldn't found GPS extrinsic parameter.

Am I missing something? 

Thanks,

**Comment by Hasar12138** [comment]
The following are the extrinsic parameters of the sequence road and forest:


os0_tf = [[0.707107,0.707107,0.0,0.0],[ -0.707107,0.707107,0.0,0.0],[0.0,0.0,1.0,0.0],[ 0.0,0.0,0.0,1.0]]

rtk_tf = [[-0.36559303,   0.93824716 , -0.04568061  , 0],   [ -0.82504324, -0.27759676 , 0.49218258 , 0], [ 0.44910812,  0.20647593, 0.87283921,0],[ 0.0,0.0,0.0,1.0]]

os1_tf = [[0.728751,-0.684722,0.00880163,-0.0118653],[  0.68459,0.728792,0.0140687,-0.568633],
                [ -0.0160477, -0.00422711,0.999862 ,-0.00518761],[ 0.0,0.0,0.0,1.0]]

velo_tf = [[ 0.999046,-0.0385039,0.0206179,-0.109294],[ 0.0383028,0.999216,0.010062,-0.295213],
                    [ -0.0209891 ,-0.00926264,0.999737,0.090953],[ 0.0,0.0,0.0,1.0]]

hori_tf = [[0.999472,0.0231217 ,-0.0228489,-0.114303],[-0.0226391,0.99952,0.0211604,-0.312768],
                    [ 0.0233272,-0.020632,0.999515,-0.102705],[ 0.0,0.0,0.0,1.0]]
  
avia_tf = [[ 0.999495,0.000987174,-0.0317686,-0.106596],[ -0.000559863,0.999909,0.0134568,-0.234419],
                    [0.031779,-0.0134322,  0.999405, -0.131481],[ 0.0,0.0,0.0,1.0]]

**Comment by mertyavuz41** [comment]
Thanks for response,

I am asking to understand clearly, these extrinsic informations relative to base_link, right?  For example, rtk_tf(GPS) -> base_link
